# Generated by Django 2.0.2 on 2018-02-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='roll',
            new_name='name',
        ),
    ]
